# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: 2.1

orbs:
  win: circleci/windows@2.0.0


executors:
  linux-arm64:
    machine:
      image: ubuntu-2004:2023.10.1
      resource_class: arm.medium
    working_directory: ~/typedb

  linux-x86_64:
    machine:
      image: ubuntu-2004:2023.10.1
    working_directory: ~/typedb

  mac-arm64:
    macos:
      xcode: "13.4.1"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/typedb

  mac-x86_64:
    macos:
      xcode: "13.4.1"
    working_directory: ~/typedb


commands:

  install-bazel-linux-x86_64:
    steps:
      - run: |
          curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64"
          sudo mv "bazelisk-linux-amd64" /usr/local/bin/bazel
          chmod a+x /usr/local/bin/bazel

  install-bazel-linux-arm64:
    steps:
      - run: |
          curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-arm64"
          sudo mv "bazelisk-linux-arm64" /usr/local/bin/bazel
          chmod a+x /usr/local/bin/bazel

  install-bazel-mac:
    steps:
      - run: brew install bazelisk

jobs:
  test-assembly-mac-x86_64-zip:
    executor: mac-x86_64
    working_directory: ~/typedb
    steps:
      - checkout
      - install-bazel-mac
      - run: bazel test //test/assembly:assembly --test_output=errors

  test-assembly-mac-arm64-zip:
    executor: mac-arm64
    resource_class: macos.m1.medium.gen1
    working_directory: ~/typedb
    steps:
      - checkout
      - install-bazel-mac
      - run: bazel test //test/assembly:assembly --test_output=errors

  test-assembly-linux-arm64-zip:
    executor: linux-arm64
    working_directory: ~/typedb
    steps:
      - checkout
      - install-bazel-linux-arm64
      - run: bazel test //test/assembly:assembly --test_output=errors

  test-assembly-linux-x86_64-zip:
    executor: linux-x86_64
    working_directory: ~/typedb
    steps:
      - checkout
      - install-bazel-linux-x86_64
      - run: bazel test //test/assembly:assembly --test_output=errors

  test-assembly-windows-zip:
    executor:
      name: win/default
      shell: cmd.exe
    working_directory: ~/typedb
    steps:
      - checkout
      - run: .circleci\windows\prepare.bat
      - run: .circleci\windows\test-assembly.bat


workflows:
  typedb:
    jobs:
      - test-assembly-mac-x86_64-zip:
          filters:
            branches:
              only:
                - master
                - development
      - test-assembly-mac-arm64-zip:
          filters:
            branches:
              only:
                - master
                - development
      - test-assembly-linux-x86_64-zip:
          filters:
            branches:
              only:
                - master
                - development
      - test-assembly-linux-arm64-zip:
          filters:
            branches:
              only:
                - master
                - development
      - test-assembly-windows-zip:
          filters:
            branches:
              only:
                - master
                - development
